project:
  type: website
  output-dir: docs

website:
  title: "drjoseluisheram"
  navbar:
    right:
      - text: Home
        href: index.qmd
      - text: CV
        href: CV_JoseLuisHernandezRamirez.pdf
      - icon: github
        href: https://github.com/drjoseluisheram
format:
  html:
    output-file: "index"
    theme: default
